<?php
/* =====================================================================
   File    : insert_student.php
   Purpose : Receives the registration form (from add_student.php or
             Frontend/index.html), validates it on the server, saves the
             two uploaded files and inserts the record into MySQL.
   Flow    : validate -> check duplicates -> validate files -> save files
             -> INSERT students -> INSERT student_files -> success page
   ===================================================================== */
require_once 'db.php';

// This page only accepts form submissions (POST). Direct opening -> back to the form.
if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    redirect('add_student.php');
}

// If the total upload is bigger than post_max_size, PHP gives an empty $_POST.
if (empty($_POST)) {
    $_SESSION['form_errors'] = ['The uploaded data is too large. Each file must be 2 MB or less.'];
    redirect('add_student.php');
}

// ---------------- 1. Read and validate the text fields ----------------
$data   = read_student_form();
$errors = validate_student($data, false);

// ---------------- 2. Unique roll number / e-mail check ----------------
if (empty($errors)) {
    try {
        $errors = array_merge($errors, find_duplicates($conn, $data['roll_number'], $data['email']));
    } catch (mysqli_sql_exception $ex) {
        $errors[] = 'Database error while checking duplicates: ' . $ex->getMessage();
    }
}

// ---------------- 3. File validation (type + size) ----------------
$imageError = validate_upload($_FILES['profile_image'] ?? null, IMAGE_EXTENSIONS, 'Profile image', true);
$certError  = validate_upload($_FILES['certificate'] ?? null, ALL_EXTENSIONS, 'Certificate', true);
if ($imageError !== '') {
    $errors[] = $imageError;
}
if ($certError !== '') {
    $errors[] = $certError;
}

// Any error -> go back to the form and show the messages (password is not kept)
if (!empty($errors)) {
    $_SESSION['form_errors'] = $errors;
    $old = $data;
    unset($old['password']);
    $_SESSION['old_input'] = $old;
    redirect('add_student.php');
}

// ---------------- 4. Save the files in the uploads folder ----------------
$imagePath = save_upload($_FILES['profile_image']);
$certPath  = save_upload($_FILES['certificate']);

if ($imagePath === false || $certPath === false) {
    // Remove whichever file was saved so nothing is left behind
    delete_upload($imagePath ?: '');
    delete_upload($certPath ?: '');
    $_SESSION['form_errors'] = ['Could not save the uploaded files. Check that the uploads folder is writable.'];
    redirect('add_student.php');
}

// ---------------- 5. Insert into the database (transaction) ----------------
// A transaction makes sure both tables are updated together or not at all.
$conn->begin_transaction();
try {
    // Never store a plain password - password_hash() creates a secure bcrypt hash
    $passwordHash = password_hash($data['password'], PASSWORD_DEFAULT);

    // Prepared statement: "?" placeholders prevent SQL injection
    $stmt = $conn->prepare('INSERT INTO students
        (name, roll_number, email, password, course, mobile, gender, address, profile_image)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)');
    $stmt->bind_param('sssssssss',
        $data['name'], $data['roll_number'], $data['email'], $passwordHash,
        $data['course'], $data['mobile'], $data['gender'], $data['address'], $imagePath);
    $stmt->execute();
    $studentId = $conn->insert_id;     // id generated by AUTO_INCREMENT
    $stmt->close();

    // Record both uploaded files in student_files
    $fileStmt = $conn->prepare('INSERT INTO student_files (student_id, file_name, file_path, file_type)
                                VALUES (?, ?, ?, ?)');
    $uploads = [
        [$_FILES['profile_image']['name'], $imagePath],
        [$_FILES['certificate']['name'], $certPath],
    ];
    foreach ($uploads as $upload) {
        $originalName = basename($upload[0]);
        $filePath     = $upload[1];
        $fileType     = strtolower(pathinfo($filePath, PATHINFO_EXTENSION));
        $fileStmt->bind_param('isss', $studentId, $originalName, $filePath, $fileType);
        $fileStmt->execute();
    }
    $fileStmt->close();

    $conn->commit();   // everything succeeded -> make permanent

    set_flash('success', "Student {$data['name']} ({$data['roll_number']}) registered successfully.");
    redirect('student_details.php?id=' . $studentId);

} catch (mysqli_sql_exception $ex) {
    // SQL error handling: undo database changes and delete saved files
    $conn->rollback();
    delete_upload($imagePath);
    delete_upload($certPath);

    // 1062 = duplicate entry (in case two users submit the same roll number at once)
    if ($ex->getCode() == 1062) {
        $message = 'Roll number or email already exists.';
    } else {
        $message = 'Database error: ' . $ex->getMessage();
    }
    $_SESSION['form_errors'] = [$message];
    $old = $data;
    unset($old['password']);
    $_SESSION['old_input'] = $old;
    redirect('add_student.php');
}
